import { BASE, launch, newPage, signIn } from "./lib.mjs";
import { acc, db, matchesFor, poll, sleep, submitReport, svcOf } from "./helpers.mjs";
const b = await launch();
const sur = await newPage(b); await signIn(sur, "survivor");
const rid = await submitReport(sur, { first_name: "E2E-Explore", required_services: ["legal"], urgency: "high" });
await sleep(4500);
const m = (await matchesFor(rid)).find((x) => x.service_id === svcOf("professional").id);
const pro = await newPage(b); await signIn(pro, "professional");
await pro.goto(`${BASE}/dashboard/cases/${m.id}`, { waitUntil: "networkidle", timeout: 120000 });
await pro.getByRole("button", { name: /ACCEPT & SCHEDULE/i }).waitFor({ timeout: 60000 });
await pro.getByRole("button", { name: /ACCEPT & SCHEDULE/i }).click();
await pro.getByPlaceholder(/Enter an initial message/i).fill("Hello, I am your lawyer. I am here to help.");
await pro.getByRole("button", { name: "MEET NOW" }).click();
await sleep(8000);
const after = (await db.from("matched_services").select("match_status_type, chat_id").eq("id", m.id).single()).data;
console.log("match after accept:", JSON.stringify(after));
console.log("others:", JSON.stringify((await matchesFor(rid)).map((x) => x.match_status_type)));
console.log("appointments:", JSON.stringify((await db.from("appointments").select("status,appointment_type,appointment_date").eq("matched_services", m.id)).data));
console.log("survivor notifications:", JSON.stringify((await db.from("notifications").select("type,title").eq("user_id", acc("survivor").id)).data));
console.log("URL:", pro.url());
await pro.goto(`${BASE}/dashboard/cases/${m.id}`, { waitUntil: "networkidle", timeout: 120000 });
await pro.waitForTimeout(9000);
console.log((await pro.locator("body").innerText()).replace(/\n{3,}/g, "\n\n").slice(0, 1800));
console.log("BUTTONS:", await pro.getByRole("button").evaluateAll((els) => els.map((e) => (e.getAttribute("aria-label") || e.innerText || "").trim().replace(/\s+/g, " ")).filter(Boolean).slice(0, 40)));
await b.close();
